### ISSUE TITLE
Ensure PDF URL is included in DOI registration metadata FOR JOURNALS

### ISSUE THREAD

**Issue by lschiff** [eScholarship/janeway#7]
To enable use of iThenticate (Crossref’s Similarity Check), the download PDF link should be included in the metadata we are sending to Crossref when registering DOIs, for all journals currently published via Janeway and for the two preprint servers as well. Crossref has [documentation about where this goes](https://www.crossref.org/documentation/retrieve-metadata/rest-api/providing-full-text-links-to-tdm-tools/) in the metadata. For the journals, the link should be the eScholarship link; for the preprint servers, the link should be the link from the Janeway front end.

We should set this up for all prospective content published on Janeway, and then do a major update, when legacy abstracts are added (see the dependency card).

Here is the old Trello card with more details: https://trello.com/c/dx2gbsDY

**Comment by myucekul** [comment]
Add collection to the <doi_data/> element for all PDF and (where they exist) XML files:
<collection property="text-mining">
        <item>
          <resource mime_type="application/pdf">[URL]
          </resource>
        </item>

        <item>
          <resource mime_type="application/xml">[XML if needed]</resource>
        </item>

      </collection>

**Comment by myucekul** [comment]
For preprint, the url will be the download url in Janeway.
For journals, the url will the download url in jschol.

**Comment by myucekul** [comment]
For preprint: The download url is manage url that is required credentials. We need to wait for the fix to be deployed here before proceeding for the change for preprint. 
https://github.com/openlibhums/janeway/commit/9fcbbe87b917bf3c4ce1d64b85d579f7c0634069

I'll create PR with the note about download_url dependency.

**Comment by myucekul** [comment]
Since preprint part needs to wait, I'm making this card specific to journal and creating another for preprint.

**Comment by myucekul** [comment]
The changes are applied in dev, stage, and prod.
