### ISSUE TITLE
Ensure license information is included in DOI registration metadata

### ISSUE THREAD

**Issue by myucekul** [eScholarship/janeway#8]
Crossref has a specific metadata structure for surfacing text available for mining ([Crossref documentation](https://www.crossref.org/documentation/retrieve-metadata/rest-api/providing-licensing-information-to-tdm-tools/)). Our content is already open, but this is another easy way to expand its reach and also a way to improve our participation in Crossref services. We should add the appropriate snippet to to records for prospective content and submit legacy content, after/as part of migrations.

Related PR: https://github.com/eScholarship/janeway_ezid_plugin/pull/11/

**Comment by myucekul** [comment]
Created preprint with licensing: https://ezid-stg.cdlib.org/manage/display_xml/doi:10.15697/FK2994D

**Comment by myucekul** [comment]
Journal with licensing info: https://ezid-stg.cdlib.org/manage/display_xml/doi:10.15697/FK2994J

**Comment by myucekul** [comment]
https://github.com/eScholarship/janeway_ezid_plugin/pull/15

**Comment by myucekul** [comment]
PR is merged.

**Comment by myucekul** [comment]
There is a separate issue for mining info/ download. https://github.com/orgs/eScholarship/projects/1/views/6?pane=issue&itemId=78501235

**Comment by myucekul** [comment]
The changes are applied in dev, stage, and prod.

**Comment by lschiff** [comment]
Hi @myucekul  There's an error with the license info in the Crossref generation that's creating lots and lots of tickets from EZID/Crossref.  Per Adam: these are "metadata errors stemming from the use of an empty license_ref tag."  I'm going to reopen this issue.  Thanks!

**Comment by myucekul** [comment]
Created a PR to check for empty license URL.

**Comment by myucekul** [comment]
List from Jing to review and update DOI.
doi:10.15697/FK2532X
doi:10.15697/FK2WP5V
doi:10.5070/P5.35434
doi:10.5070/P5.35435
doi:10.5070/P5.35436
doi:10.5070/P5.35437
doi:10.5070/P5.35438
doi:10.5070/P5.35439
doi:10.5070/P5.35440
doi:10.5070/P5.35441
doi:10.5070/P5.35442
doi:10.5070/P5.35443
doi:10.5070/P5.35444
doi:10.5070/P5.35445
doi:10.5070/P5.35446
doi:10.5070/P5.35447
doi:10.5070/P5.35448
doi:10.15697/FK27316
doi:10.15697/FK2ZK6T

**Comment by myucekul** [comment]
PR is reviewed, merged, and deployed.
